### ISSUE TITLE
Follow up on questions regarding servicePublishingStrategy

### ISSUE THREAD

**Issue by larsks** [innabox/issues#1]
A `HostedCluster` resource has a `services` stanza that describes how various cluster services are externally exposed. As generated by the `hcp` command line, it looks something like this:

```
  services:
    - service: APIServer
      servicePublishingStrategy:
        nodePort:
          address: api.london.int.massopen.cloud
        type: NodePort
    - service: Ignition
      servicePublishingStrategy:
        nodePort:
          address: api.london.int.massopen.cloud
        type: NodePort
    - service: Konnectivity
      servicePublishingStrategy:
        nodePort:
          address: api.london.int.massopen.cloud
        type: NodePort
    - service: OAuthServer
      servicePublishingStrategy:
        nodePort:
          address: api.london.int.massopen.cloud
        type: NodePort
    - service: OIDC
      servicePublishingStrategy:
        nodePort:
          address: api.london.int.massopen.cloud
        type: NodePort
```

Available publish strategies include `NodePort`, `LoadBalancer`, and `Route`. My experience is that there is some services can only be exposed using some publishing strategies, but I haven't been able to find any documentation on the topic. Follow up on `#hypershift-project` to see if we can get some authoritative information.

**Comment by larsks** [comment]
For example, if we set up a hosted cluster using exclusively the `LoadPort` publishing strategy:

```
  services:
    - service: APIServer
      servicePublishingStrategy:
        loadBalancer:
          hostname: api.london.int.massopen.cloud
        type: LoadBalancer
    - service: Ignition
      servicePublishingStrategy:
        loadBalancer:
          hostname: ignition.london.int.massopen.cloud
        type: LoadBalancer
    - service: Konnectivity
      servicePublishingStrategy:
        loadBalancer:
          hostname: konnectivity.london.int.massopen.cloud
        type: LoadBalancer
    - service: OAuthServer
      servicePublishingStrategy:
        loadBalancer:
          hostname: oauth.london.int.massopen.cloud
        type: LoadBalancer
    - service: OIDC
      servicePublishingStrategy:
        nodePort:
          address: api.london.int.massopen.cloud
        type: NodePort
```

It never deploys...but there are no errors posted to the HostedCluster resource. In fact, this condition on the HostedCluster resource explicitly declares the configuration to be valid:

```
    {
      "lastTransitionTime": "2025-02-01T01:45:04Z",
      "message": "Configuration passes validation",
      "observedGeneration": 1,
      "reason": "AsExpected",
      "status": "True",
      "type": "ValidConfiguration"
    },
```
