### ISSUE TITLE
Add functionality to create and delete layer 3 network components

### ISSUE THREAD

**Issue by larsks** [innabox/issues#103]
We will need to create layer 3 components in ESI in order to support clusters on isolated networks. That means in addition to the layer 2 network provided by #89, we also need to:

- Create a router
- Create a subnet
- Attach the subnet to the router

We will also need to figure out how to handle subnet cidr allocation. For the purposes of POC3 we can probably choose one of either "pick a random cidr" or "always use the same cidr", but we're going to want more flexibility in the future:

- We need to support a block list or allow list (or both) so that cidr allocations don't conflict with private address space already in use in the datacenter (e.g., the NESE storage network)

- We probably want to ensure that each new network has a unique cidr allocation; this would allow us to create L3 connections between networks.

**Comment by tzumainn** [comment]
Subnets: https://github.com/innabox/cloudkit-aap/pull/30

**Comment by tzumainn** [comment]
Routers: https://github.com/innabox/cloudkit-aap/pull/31

**Comment by tzumainn** [comment]
Update destroy tasks so subnets delete ports, and networks delete subnets: https://github.com/innabox/cloudkit-aap/pull/32

**Comment by tzumainn** [comment]
@larsks Should creating a network automatically create a subnet/router? Or maybe do so optionally if a parameter is specified?

**Comment by larsks** [comment]
> Should creating a network automatically create a subnet/router? Or maybe do so optionally if a parameter is specified?

I think we should have separate roles for L2 and L3 operations, and they shouldn't call each other.

Maybe we want a higher-level integration role that can be used by playbooks that need both services?

**Comment by tzumainn** [comment]
I guess that calls into question whether we want the "destroy network" playbook to actually automatically delete associated subnets?

**Comment by larsks** [comment]
> I guess that calls into question whether we want the "destroy network" playbook to actually automatically delete associated subnets?

It does! I was thinking about that yesterday myself.

**Comment by tzumainn** [comment]
> > I guess that calls into question whether we want the "destroy network" playbook to actually automatically delete associated subnets?
> 
> It does! I was thinking about that yesterday myself.

... and here's why I think we should still do it! Deleting a network through the openstack role will already attempt to delete associated subnets; it just flat out fails to do so if the subnets have associated ports. Which is to say that it feels like OpenStack L2/L3 is already entangled somewhat, and in my mind it's better to be consistent about that entanglement.

**Comment by larsks** [comment]
> ... and here's why I think we should still do it! Deleting a network through the openstack role will already attempt to delete associated subnets; it just flat out fails to do so if the subnets have associated ports.

But that just means we need to pair setup/teardown of L3 resources with setup/teardown of L2 resources.

I think I would not have separate roles for `router` and `subnet`; I think I would have one role for l2 setup, which we have now in the `network` role, and that a second role for l3 setup, so that creating a cluster would include something like:

```
- include_role:
    name: massopencloud.esi.l2setup
  vars:
    l2setup_state: present
    l2setup_name_or_id: mynetwork

- include_role:
    name: massopencloud.esi.l3setup
  vars:
    l3setup_state: present
    l3setup_name_or_id: mynetwork
```

And deleting things would reverse that:

```
- include_role:
    name: massopencloud.esi.l3setup
  vars:
    l3setup_state: absent
    l3setup_name_or_id: mynetowrk

- include_role:
    name: massopencloud.esi.l2setup
  vars:
    l2setup_state: absent
    l2setup_name_or_id: mynetwork

```

Perhaps we would introduce a higher-level `network` role that does both of those things, so that from the perspective of our playbooks we would have:

```
- include_role:
    name: massopencloud.esi.network
  vars:
    network_state: absent
    network_name_or_id: "{{ create_network_result }}"
```

And similarly for teardown, but internally that role would be calling out to the separate l2 and l3 roles.
