### ISSUE TITLE
Add node count to clusterorder crd status

### ISSUE THREAD

**Issue by larsks** [innabox/issues#117]
We need the CRD to support node count information in the status attribute. Maybe:

```
status:
  nodeCounts:
  - resourceClass: foo
    numberOfNodes: 4
```

**Comment by mhrivnak** [comment]
I'd suggest something like this, which leaves the door open for additional status fields per resource class beyond just the raw node count.

```
status:
  resourceClasses:
  - name: foo
    nodeCount: 4
```
