### ISSUE TITLE
Grant required permissions to the service account used by the fulfillment service to get kubeconfigs

### ISSUE THREAD

**Issue by jhernand** [innabox/issues#128]
In order to fetch kubeconfigs the fulfillment service needs to have the following permissions:

- Create/retrieve/update/delete `ClusterOrder` instances.
- Retrieve `HostedCluster` instances (in all namespaces).
- Retrieve `Secret` instances (in all namespaces).

To achieve that currently we created the following cluster role and binding manually:

```yaml
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fulfillment-service
rules:

# Needs permission to create, update and delete cluster orders:
- apiGroups:
  - cloudkit.openshift.io
  resources:
  - clusterorders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# In order to get the kubeconfig it needs permissions to read the hosted
# cluster, as it contains the reference to the secret that contains the
# kubeconfig.
- apiGroups:
  - hypershift.openshift.io
  resources:
  - hostedclusters
  verbs:
  - get
  - list
  - watch

# It needs permission to read the secret containing the kubeconfig.
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fulfillment-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fulfillment-service
subjects:
- kind: ServiceAccount
  name: fulfillment-service
  namespace: cloudkit-operator-system
```

This needs to be created in such a way that it is permanent, maybe as part of the deployment of the Kubernetes operator.
