### ISSUE TITLE
Run ansible cluster create/delete with limited set of rights

### ISSUE THREAD

**Issue by adriengentil** [innabox/issues#66]

**Comment by adriengentil** [comment]
@larsks , I manged to get a service account `cloudkit-sa` in `fulfillment-aap` (the service account that would be used by Ansible) to impersonate a service account `serviceaccount` in `cluster-2` namespace with the following manifests:

```
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount
  namespace: cluster-2
---
# Give some right to "serviceaccount" to read hostedclusters
apiVersion : rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: serviceaccount-role
  namespace: cluster-2
rules:
- apiGroups: ["hypershift.openshift.io"]
  resources: ["hostedclusters"]
  verbs: ["get", "watch", "list"]
---
apiVersion : rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: serviceaccount-role-binding
  namespace: cluster-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: serviceaccount-role
subjects:
- kind: ServiceAccount
  name: serviceaccount
  namespace: cluster-2
---
# Allow "serviceaccount" to be impersonated by "cloudkit-sa" in "fulfillment-app" namespace
apiVersion : rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: serviceaccount-role-aap
  namespace: cluster-2
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  resourceNames: ["serviceaccount"]
  verbs: ["impersonate"]
---
apiVersion : rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: serviceaccount-rolebinding-aap
  namespace: cluster-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: serviceaccount-role-aap
subjects:
- kind: ServiceAccount
  name: cloudkit-sa
  namespace: fulfillment-aap
```

Basically, we need the last `Role` and `RoleBinding` to allow the service account for the cluster to be impersonated by another service account.

I need to test the full flow with Ansible, but I would like to have your opinion and see if we can integrate that in the operator.
